### ISSUE TITLE
Crash when downloading on SDK 29

### ISSUE THREAD

**Issue by nana-desu** [SIARAY/DownloadManagerPlus#6]
```JAVA
E/FOLDER: /storage/emulated/0/Download
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.IllegalStateException: Not one of standard directories: /Download
        at android.os.Parcel.createException(Parcel.java:2079)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:558)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:546)
        at android.app.DownloadManager$Request.setDestinationInExternalPublicDir(DownloadManager.java:567)
        at ir.siaray.downloadmanagerplus.classes.Downloader.startDownload(Downloader.java:242)
        at ir.siaray.downloadmanagerplus.classes.Downloader.start(Downloader.java:173)
        at com.usamin.nekopoi.Activity.BrowserActivity.downloadRequest(BrowserActivity.kt:178)
        at com.usamin.nekopoi.Activity.BrowserActivity.access$downloadRequest(BrowserActivity.kt:44)
        at com.usamin.nekopoi.Activity.BrowserActivity$onCreate$3.onDownloadStart(BrowserActivity.kt:132)
        at ic.a(PG:548)
        at An.handleMessage(PG:25)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by nana-desu** [comment]
ok.. i couldn't find to solve on google for SDK 29, so currently i do by downgrading the SDK to 28.
